### ISSUE TITLE
Feature request: Memory usage

### ISSUE THREAD

**Issue by Floppy** [igorkasyanchuk/rails_performance#104]
Have you considered tracking memory usage over time? Having a graph of that would be amazing for debugging performance issues like memory leaks!

**Comment by igorkasyanchuk** [comment]
Good idea, perhaps me, you or someone can do it

**Comment by igorkasyanchuk** [comment]
but it can be a bit tricky if we consider multiple instances that can be running, also how to collect info when we don't have any requests (some thread/workers started?)

if someone decide to work on it I'm ready to talk and discuss possible solution.

**Comment by Floppy** [comment]
Looks like https://github.com/zombocom/get_process_mem provides an easy way to get the memory usage of the current process; perhaps a minimal version of this could be to store the usage along with each request or sidekiq job. It would then need multiple lines on the graph, one for each process, I guess.

If that works, then a follow up could be to look at adding a monitoring thread for regular measurements, perhaps.

**Comment by Floppy** [comment]
Actually, presumably I could work out if this is viable using `custom_data_proc` before forking and digging into the code proper... I'll have a go.

**Comment by Floppy** [comment]
So, this code is happily grabbing the PID and memory usage on each request:

```
    config.custom_data_proc = proc do |env|
      {
        pid: Process.pid,
        memory_usage: GetProcessMem.new.bytes
      }
    end
```

And I can see it in the UI:

<img width="726" alt="Screenshot 2024-11-01 at 16 44 01" src="https://github.com/user-attachments/assets/f425f1c7-4e8f-4314-9bc8-69e0cc5b11ed">

So, now I need to work out how to add a graph.

**Comment by igorkasyanchuk** [comment]
how accurate is the value of used memory?

I'm actually working on this feature, I this branch https://github.com/igorkasyanchuk/rails_performance/tree/memory_cpu_storage

but want to hear your opinion

**Comment by Floppy** [comment]
The size I'm getting with that code matches the resident size shown in `top` for the same process, so I think it's pretty accurate! Very cool to see the branch in progress, it's going to be great to be able to see the change in memory over time.

Thanks for creating this whole thing btw, I've already found it incredibly useful!

**Comment by igorkasyanchuk** [comment]
@Floppy please try this

in your Gemfile

```ruby
gem "sys-filesystem"
gem "sys-cpu"
gem "get_process_mem"
gem "rails_performance", "1.4.0.alpha1"
```

and deploy

**Comment by Floppy** [comment]
This is looking really great! Running in dev, it's reporting nicely for the stuff I've got running. Currently having problems building a docker image with it on `armhf`, which I need to do for my production test, but it looks really promising!

In my earlier experiment I had the different PIDs; is there a need for multiple CPU/Mem traces for different processes and threads? If you *can* do multiple traces, it might be easier to see what's going on by combining the app and sidekiq sections into one set of charts as well.

**Comment by igorkasyanchuk** [comment]
Not sure if I understand your situation with 2 PIDS. If you have 2 processes, maybe you can start them using different env variables.

Combining charts can be done later; now, I expect they will be one after the other. Is this something that you saw?

I think I'll release what I have already, I just need to check if the ENV variable with server ID will work as I expect when I deploy my app using kamal.

I already have this running in prod for one simple app, so far everything works fine.

BTW new version "alpha2" was released with minor tweaks and changed in the readme (check it too to see how you can configure it).

**Comment by Floppy** [comment]
Yeah don't worry about the multiple PID thing, I'm not even sure I'm thinking about it right myself. 😁

**Comment by Floppy** [comment]
So, in my system tab, I have two sections; rails,web at the top, and sidekiq,background at the bottom.

However, I actually have two sidekiq processes running, which you can see in the log here:

```
12:18:52 rails.1              | Server: Mac.lan, Context: rails, Role: web, data: {:cpu=>{:one_min=>2.21875, :five_min=>2.39697265625, :fifteen_min=>2.30419921875}, :memory=>54099968, :disk=>{:available=>477429272576, :total=>994662584320, :used=>517233311744}}
12:18:53 default_worker.1     | 2024-11-21T12:18:53.021Z pid=88594 tid=1ozy INFO: Server: Mac.lan, Context: sidekiq, Role: background, data: {:cpu=>{:one_min=>2.21875, :five_min=>2.39697265625, :fifteen_min=>2.30419921875}, :memory=>64323584, :disk=>{:available=>477429272576, :total=>994662584320, :used=>517233311744}}
12:18:53 performance_worker.1 | 2024-11-21T12:18:53.074Z pid=88595 tid=1oz7 INFO: Server: Mac.lan, Context: sidekiq, Role: background, data: {:cpu=>{:one_min=>2.21875, :five_min=>2.39697265625, :fifteen_min=>2.30419921875}, :memory=>60129280, :disk=>{:available=>477429272576, :total=>994662584320, :used=>517233311744}}
12:19:52 rails.1              | Server: Mac.lan, Context: rails, Role: web, data: {:cpu=>{:one_min=>2.0546875, :five_min=>2.33349609375, :fifteen_min=>2.28662109375}, :memory=>62357504, :disk=>{:available=>477428736000, :total=>994662584320, :used=>517233848320}}
12:19:53 default_worker.1     | 2024-11-21T12:19:53.027Z pid=88594 tid=1ozy INFO: Server: Mac.lan, Context: sidekiq, Role: background, data: {:cpu=>{:one_min=>2.0546875, :five_min=>2.33349609375, :fifteen_min=>2.28662109375}, :memory=>63193088, :disk=>{:available=>477428736000, :total=>994662584320, :used=>517233848320}}
12:19:53 performance_worker.1 | 2024-11-21T12:19:53.083Z pid=88595 tid=1oz7 INFO: Server: Mac.lan, Context: sidekiq, Role: background, data: {:cpu=>{:one_min=>2.0546875, :five_min=>2.33349609375, :fifteen_min=>2.28662109375}, :memory=>59408384, :disk=>{:available=>477428736000, :total=>994662584320, :used=>517233848320}}
12:20:52 rails.1              | Server: Mac.lan, Context: rails, Role: web, data: {:cpu=>{:one_min=>1.94287109375, :five_min=>2.25390625, :fifteen_min=>2.25732421875}, :memory=>51953664, :disk=>{:available=>477426073600, :total=>994662584320, :used=>517236510720}}
12:20:53 default_worker.1     | 2024-11-21T12:20:53.036Z pid=88594 tid=1ozy INFO: Server: Mac.lan, Context: sidekiq, Role: background, data: {:cpu=>{:one_min=>1.94287109375, :five_min=>2.25390625, :fifteen_min=>2.25732421875}, :memory=>59932672, :disk=>{:available=>477426077696, :total=>994662584320, :used=>517236506624}}
12:20:53 performance_worker.1 | 2024-11-21T12:20:53.091Z pid=88595 tid=1oz7 INFO: Server: Mac.lan, Context: sidekiq, Role: background, data: {:cpu=>{:one_min=>1.94287109375, :five_min=>2.25390625, :fifteen_min=>2.25732421875}, :memory=>56901632, :disk=>{:available=>477426057216, :total=>994662584320, :used=>517236527104}}
```

I guess both default_worker and performance_worker are getting combined into the same sidekiq,background trace?

**Comment by igorkasyanchuk** [comment]
Can you try to fork my branch and play with ENV variables here

https://github.com/igorkasyanchuk/rails_performance/pull/111/files#diff-d12e13cc95f166079225a1d9c8f12bbcabf0cfa85a2378f398717552e9f80034R52

Right now as you see I have "sidekiq" as hardcoded string.

Maybe you can put something like

```
 RailsPerformance._resource_monitor = RailsPerformance::Extensions::ResourceMonitor.new("sidekiq", ENV["RAILS_PERFORMANCE_ROLE"].presence || "background")
```

like I did above and somehow specify it for different processes

**Comment by igorkasyanchuk** [comment]
oh I haven't pushed alpha2 version (just not near my computer), but I think you understand the idea

**Comment by Floppy** [comment]
OK, I'll take a look at it later on, but I've just found (and verified) that foreman and overmind (and maybe others?) set the `PS` environment variable with the name. That might be worth checking by default?

**Comment by igorkasyanchuk** [comment]
only if you can check it, I really don't have the capacity :) I'll try to solve my case, and then wait for the community with improvements )

**Comment by Floppy** [comment]
that's fine, I will have a go later :)
