### ISSUE TITLE
Stops working after awhile

### ISSUE THREAD

**Issue by rezart** [igorkasyanchuk/rails_performance#15]
The gem worked well initially but then just stopped displaying any metrics. I tried restarting puma but still no metrics, and the recent requests tab remains empty. Attaching a screenshot of what I see when I visit the metrics page.

![image](https://user-images.githubusercontent.com/1059379/103327827-1148a000-4a0b-11eb-967e-725af790c0ec.png)

**Comment by igorkasyanchuk** [comment]
it might be a bug with timezones, maybe
not sure
after restart does it work?

try to reduce the duration to 1-2 hours of collected data

ideally, if you can make a fix it would be nice

**Comment by igorkasyanchuk** [comment]
cannot reproduce
