### ISSUE TITLE
[PR] CI for tests

### ISSUE THREAD

**Issue by GWillmann** [igorkasyanchuk/rails_performance#16]
Hello @igorkasyanchuk,

Thanks for your work on this Gem!

I would like to work on this task in the TODO : `CI for tests`.

Which CI app did you have in mind? I see there is already a .travis.yml file in the project root. 

Let me know if you had something in particular in mind please :)

**Comment by igorkasyanchuk** [comment]
Hi @GWillmann, I think the best is github actions. Recently one developer added it on abothter my gem - active_storage_validations

**Comment by igorkasyanchuk** [comment]
added github actions
