### ISSUE TITLE
seems to not work with Grape

### ISSUE THREAD

**Issue by jstdoit** [igorkasyanchuk/rails_performance#24]
Hi,
Thanks for your work! I found it does not work with Grape, when I run many requests of Grape's Api, there is none one of them.

**Comment by igorkasyanchuk** [comment]
Hi, probably it's not generating an "instrumentation" info as it works in rails.
Maybe it's easy to add support for grape but investigation is needed.
Please try to see what you can do by yourself

**Comment by igorkasyanchuk** [comment]
this could be used
https://github.com/ruby-grape/grape/blob/7741f022b5928f0ddcee27de08555d95ea4556f8/README.md#active-support-instrumentation
