### ISSUE TITLE
Using with redis cluster

### ISSUE THREAD

**Issue by strelok1111** [igorkasyanchuk/rails_performance#25]
I tried using this gem with redis cluster, and get error in this method
```   
  def Utils.fetch_from_redis(query)
      #puts "\n\n   [REDIS QUERY]   -->   #{query}\n\n"

      keys   = RP.redis.keys(query)
      return [] if keys.blank?
      values = RP.redis.mget(keys)

      [keys, values]
    end
```
Redis::CommandError (CROSSSLOT Keys in request don't hash to the same slot)

then I change to this and all work

```
  def Utils.fetch_from_redis(query)
      #puts "\n\n   [REDIS QUERY]   -->   #{query}\n\n"

      keys   = RP.redis.keys(query)
      return [] if keys.blank?
      values = keys.collect { |k| RP.redis.get(k) }

      [keys, values]
    end
```

**Comment by igorkasyanchuk** [comment]
can this help https://aws.amazon.com/premiumsupport/knowledge-center/elasticache-crossslot-keys-error-redis/ ?

` values = keys.collect { |k| RP.redis.get(k) }` because it will make a X amount of requests to the redis and probably it's not well optimized

**Comment by strelok1111** [comment]
I'm not familiar with redis, just want it to work.

**Comment by haffla** [comment]
I haven't tested this. But reading the article posted by @igorkasyanchuk I think a very simple solution would be to change https://github.com/igorkasyanchuk/rails_performance/blob/master/lib/rails_performance.rb#L26

from

```ruby
@@redis = Redis::Namespace.new("#{::Rails.env}-rails-performance", redis: Redis.new
```

to

```ruby
  @@redis = Redis::Namespace.new("{#{::Rails.env}-rails-performance}", redis: Redis.new)
```

This should guarantee that all `rails_performance` redis keys are going to end up in the same slot. @strelok1111 could you test this?

**Comment by strelok1111** [comment]
Just test in production, changing config file make this gem work with redis cluster.
 @haffla thank you for simple solution. I think this case need to add in documentation.

**Comment by igorkasyanchuk** [comment]
@haffla if you can prepare a PR with fix or documentation it would be great. I'm closing this issue for now
