### ISSUE TITLE
Exception when `serve_static_files` is disabled

### ISSUE THREAD

**Issue by ivanyv** [igorkasyanchuk/rails_performance#29]
In such case, `ActionDispatch::Static` does not exist, causing an exception in https://github.com/igorkasyanchuk/rails_performance/blob/master/lib/rails_performance/engine.rb#L16.

Not sure if conditionally using `Rack::Sendfile` when appropriate or using `insert_before Rack::Lock` would make more sense.

**Comment by igorkasyanchuk** [comment]
hello @ivanyv 
please try to clone repo and connect in your app and try
if it works you can try to make a PR or I'll make a fix. I just want to know if this is a working solution

**Comment by igorkasyanchuk** [comment]
@ivanyv how you are disabling this setting? how to reproduce

**Comment by ivanyv** [comment]
@igorkasyanchuk in `config/environments/X.rb`, `config.serve_static_files = false`

**Comment by igorkasyanchuk** [comment]
I've in all apps 
`config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?`

and this RAILS_SERVE_STATIC_FILES is not present

so I think it's false by default.

I'm asking because maybe you have some code where you are deleting middleware.

![image](https://user-images.githubusercontent.com/11101/115907794-01e5da80-a472-11eb-9c9c-bd7116f84a11.png) and this options is explicitly false in prod config.

**Comment by ivanyv** [comment]
There could be that some library is removing that middleware but I'm not doing it explicitly. FWIW, setting that config to true fixes the issue.

**Comment by igorkasyanchuk** [comment]
try the new version, it has new features plus I've added a fix for your problem

  gem 'rails_performance', '1.0.0.beta5'

**Comment by ivanyv** [comment]
Will do, thanks!

**Comment by igorkasyanchuk** [comment]
does it work? @ivanyv

**Comment by igorkasyanchuk** [comment]
new version released, I think now should work

**Comment by ivanyv** [comment]
@igorkasyanchuk sorry it took me a bit to look at this again; it doesn't work yet because the middleware insertion happens later, so I think a better solution could be:
```ruby
after = app.config.serve_static_files ? ActionDispatch::Static : Rack::SendFile
app.middleware.insert_after after, RailsPerformance::Rails::Middleware
```

**Comment by igorkasyanchuk** [comment]
@ivanyv @salzig please it someone can create a PR it would be nice. I just can't handle it now.
Thank you
