### ISSUE TITLE
rake tasks causing errors when redis is not available even when RailsPerformance.setup config has `enabled = false`

### ISSUE THREAD

**Issue by carlost** [igorkasyanchuk/rails_performance#32]
app uses:
- rails_performance v1.0.0
- rails v6.0.3.x app
- bundler v2.2.16
- ruby 2.7.2

App has disabled RailsPerformance in initialization file but still includes it as dependency in Gemfile scope.

What i originally posted as the cause of the issue was wrong ... because i was talking about RailsPerformance code that I added to the gem while debugging this :)

The rake task extension never checks to see if RailsPerformance is enable ... so it will always run and capture data.

This should respect the apps config settings.

**Comment by carlost** [comment]
I am not sure what a clean solution to this might be.  We don't need to instrument our rake tasks, so we just monkey patched Rake::Task to remove the RailsPerformance instrumentation.  If we needed to instrument rarke I think our solution would have been to:
- update the `#invoke` method in rake_ext.rb to check `RailsPerformance.enabled` before instrumenting a rake call and,
- default RailsPerformance.enabled to false ... that way rake tasks invoked before the rails env is loaded and before the rails_perrformance initialization file is required will not trigger instrumentation.

**Comment by igorkasyanchuk** [comment]
@carlost can you prepare a PR?

**Comment by haffla** [comment]
Didn't I fix that in https://github.com/igorkasyanchuk/rails_performance/pull/30?

@igorkasyanchuk could you create a new release that includes it?

**Comment by igorkasyanchuk** [comment]
sorry for a delay,
new version rails_performance-1.0.1.gem just released
thanks!
