### ISSUE TITLE
No Data...how to debug?

### ISSUE THREAD

**Issue by philsmy** [igorkasyanchuk/rails_performance#35]
We followed the basic installation. Redis is running (we use it for other process and they are fine) but we see no data in the dashboard. Is there any way to debug what is going on?

It seems the debug flag, which turns on logging, doesn't matter because nothing logs that I can find.

**Comment by igorkasyanchuk** [comment]
Hello @philsmy 
I suggest to clone the repo and add the gem to your app with `gem 'rails_performance', path: '../rails_performance'` for example

after this you can try to debug and see what is pushed to redis (what key name), and compare with query to the redis

**Comment by igorkasyanchuk** [comment]
let me know how it works for you

**Comment by igorkasyanchuk** [comment]
assuming now that all is ok
