### ISSUE TITLE
handle case when redis is out of memory - Redis::OutOfMemoryError

### ISSUE THREAD

**Issue by emish89** [igorkasyanchuk/rails_performance#46]
Hi all,
When redis is out of memory the rails performance gem seems giving an unhandled exception that break the api calls.
The exception is the Redis::OutOfMemoryError but I don't have any other info.
I can reproduce it filling the whole cache and trying to make a call.
thanks a lot for the help

**Comment by igorkasyanchuk** [comment]
I suggest reducing `config.duration = 4.hours` which is captured (or upgrade to more RAM). Nothing else can't be done
