### ISSUE TITLE
undefined method `devise_for' in new version 1.0.5.1

### ISSUE THREAD

**Issue by emish89** [igorkasyanchuk/rails_performance#48]
Hi, 
in the last version I get an error on startup on 

`/.rvm/gems/ruby-3.0.5/gems/rails_performance-1.0.5.1/config/routes.rb:2:in block in <top (required)>': undefined method devise_for' for #<ActionDispatch::Routing::Mapper:0x00007fa76a9c1d50 @set=#<ActionDispatch::Routing::RouteSet:0x00007fa771bd90c8>, @draw_paths=[#<Pathname:/.rvm/gems/ruby-3.0.5/gems/rails_performance-1.0.5.1/config/routes>], @scope=#<ActionDispatch::Routing::Mapper::Scope:0x00007fa76a9c1cd8 @hash={:path_names=>{:new=>"new", :edit=>"edit"}}, @parent=#<ActionDispatch::Routing::Mapper::Scope:0x00007fa7691490e8 @hash=nil, @parent=nil, @scope_level=nil>, @scope_level=nil>, @concerns={}> (NoMethodError)`

I see in the confi/routes.rb file this new line `devise_for :users` that is causing the error. 

Why it was introduced? 
Thanks for the help

**Comment by igorkasyanchuk** [comment]
Hi, try 1.0.5.2, should be fixed
