### ISSUE TITLE
When there is a lot of requests, "Recent Requests" page stuck while loading on browser

### ISSUE THREAD

**Issue by AliOsm** [igorkasyanchuk/rails_performance#49]
I was performing some load test on my website, and I submitted 2K requests on it. The Recent Requests tab stuck when I open it because of the huge list of requests it loads. How to configure the default number of requests it loads on the beginning?

**Comment by igorkasyanchuk** [comment]
Right now now way to do it. Good feature to implement in the future

**Comment by AliOsm** [comment]
Could you provide some code pointers so I can implement it and submit the PR?

**Comment by igorkasyanchuk** [comment]
Clone repo, start dummy app inside and run few requests, after that change code. I think you would need to add some "max_requests" value and just limit arrays to this size

**Comment by igorkasyanchuk** [comment]
try this version, has 2 new options

  # config.recent_requests_time_window = 60.minutes
  # config.recent_requests_limit = nil # or 1000


 rails_performance-1.0.5.3.gem
