### ISSUE TITLE
Error on  ruby '2.4.7'  and 'rails', '4.2.8'

### ISSUE THREAD

**Issue by luispimenta** [igorkasyanchuk/rails_performance#5]
Error on rails s 

.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/rails_performance-0.9.2/lib/rails_performance/engine.rb:10:in `<class:Engine>': uninitialized constant ActionDispatch::Executor (NameError)
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/rails_performance-0.9.2/lib/rails_performance/engine.rb:6:in `<module:RailsPerformance>'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/rails_performance-0.9.2/lib/rails_performance/engine.rb:5:in `<top (required)>'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/rails_performance-0.9.2/lib/rails_performance.rb:61:in `<top (required)>'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `require'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `each'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:76:in `block in require'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `each'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler/runtime.rb:65:in `require'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/bundler-1.17.3/lib/bundler.rb:114:in `require'
ruby/motorsw-web/config/application.rb:8:in `<top (required)>'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `require'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:78:in `block in server'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `tap'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:75:in `server'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
ruby/motorsw-web/bin/rails:9:in `require'
ruby/motorsw-web/bin/rails:9:in `<top (required)>'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `load'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/client/rails.rb:28:in `call'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/client/command.rb:7:in `call'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/client.rb:30:in `run'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/bin/spring:49:in `<top (required)>'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `load'
.rbenv/versions/2.4.7/lib/ruby/gems/2.4.0/gems/spring-2.0.0/lib/spring/binstub.rb:31:in `<top (required)>'
.rbenv/versions/2.4.7/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
.rbenv/versions/2.4.7/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:68:in `require'
from /ruby/motorsw-web/bin/spring:13:in `<top (required)>'
from bin/rails:3:in `load'
from bin/rails:3:in `<main>'

**Comment by igorkasyanchuk** [comment]
@luispimenta  can you try to fork and make a fix?
https://github.com/igorkasyanchuk/rails_performance/blob/master/lib/rails_performance/engine.rb#L10

Check what is the first middleware to insert this for Rails < 5.

**Comment by igorkasyanchuk** [comment]
Okay, I've added support for Rails 4.2 (and maybe earlier versions).
Use v 0.9.3 and tell me if it works for you

**Comment by luispimenta** [comment]
> Okay, I've added support for Rails 4.2 (and maybe earlier versions).
> Use v 0.9.3 and tell me if it works for you

Works ! Thank you
