### ISSUE TITLE
depend on ralties instead of rails

### ISSUE THREAD

**Issue by langalex** [igorkasyanchuk/rails_performance#60]
By making rails a dependency, any app adding this gem will inherit all the Rails gems such as activerecord, actioncable, actionmailer, activestorage etc., even if it is not using these optional dependencies itself.

By changing the dependency to just railties, no optional Rails dependencies are forced upon apps.

**Comment by igorkasyanchuk** [comment]
@langalex can you please create a PR? In general, I agree with you. It was just easier.

**Comment by langalex** [comment]
thanks! ❤️
