### ISSUE TITLE
Any plans to support p99?

### ISSUE THREAD

**Issue by AliOsm** [igorkasyanchuk/rails_performance#71]
I was wonderring if there are any plans to support p99 beside the average latency.

**Comment by igorkasyanchuk** [comment]
@AliOsm  added, try to upgrade

<img width="1897" alt="image" src="https://github.com/user-attachments/assets/f97ba8a0-af2a-4e13-a2c1-88630685bb41">

<img width="1305" alt="image" src="https://github.com/user-attachments/assets/514c9165-3490-4983-b250-25c3190ac481">

**Comment by AliOsm** [comment]
@igorkasyanchuk Any reasons why `redis-namespace` dependency removed? It is causing `uninitialized constant Redis::Namespace` error because `Redis::Namespace` is used in the initializer.

**Comment by igorkasyanchuk** [comment]
Please change your config. It's not needed. Unless you really have a need, you can add it back as dependency

**Comment by AliOsm** [comment]
Then the README should be updated also 😅
