### ISSUE TITLE
helper methods in this gem collide with own helper methods

### ISSUE THREAD

**Issue by mastermoo** [igorkasyanchuk/rails_performance#9]
The helper methods used in this [file](https://github.com/igorkasyanchuk/rails_performance/blob/master/app/helpers/rails_performance_helper.rb) override methods in our own app.

For example, when when calling the method `icon`, instead of our own my implementation, the method from this gem is called.

Does it make sense to just give each helper method in this gem a prefix, so that it won't override any methods of the main app? for e.g. renaming `icon` to `rails_performance_icon`.

**Comment by igorkasyanchuk** [comment]
hi @mastermoo 
try now new version: rails_performance (0.9.5) and let me know how it works

**Comment by mastermoo** [comment]
wow, yeah it works perfectly, thanks for taking care of it so quickly!
