### ISSUE TITLE
Inconsistent use of Time.now in ActiveSupport and Time.current in rails_performance

### ISSUE THREAD

**Issue by MikhailVerbitski** [igorkasyanchuk/rails_performance#94]
ActiveSupport uses Time.now, which returns the system time without taking into account the Rails application's time zone when the request is completed:
<img width="582" alt="Screenshot 2024-10-15 at 01 26 28" src="https://github.com/user-attachments/assets/f3ed46b9-f051-4eb0-896e-399cf8c253e5">

Thus, the data in the redis is created with local time.

However, when reading data from the redis, Time.current is used, which makes the data completely unavailable for a certain period of time around midnight, depending on your time zone:
<img width="1084" alt="Screenshot 2024-10-15 at 01 28 14" src="https://github.com/user-attachments/assets/fae54e1a-b3e8-4f96-835b-e1d24d98fd46">

**Comment by MikhailVerbitski** [comment]
gh pr checkout 95

**Comment by igorkasyanchuk** [comment]
Please try this version 

gem "rails_performance", "1.4.0.alpha4"

(or branch above)

**Comment by igorkasyanchuk** [comment]
I hope now it's fixed
